export const INVENTORY_CONSTANTS = {
  DEFAULT_SAFETY_BUFFER_PERCENT: 10,
  DEFAULT_RESERVATION_MINUTES: 15,
  SHORT_EXPIRY_DAYS: 180,
  LOW_STOCK_THRESHOLD: 10,
  EXPIRY_ALERT_DAYS: [30, 60, 90, 180],
  QUARANTINE_STATUS: 'QUARANTINE',
  RESERVATION_STATUS: {
    RESERVED: 'RESERVED',
    RELEASED: 'RELEASED',
    DEDUCTED: 'DEDUCTED',
    EXPIRED: 'EXPIRED'
  },
  STOCK_STATUS: {
    IN_STOCK: 'IN_STOCK',
    LOW: 'LOW',
    OUT_OF_STOCK: 'OUT_OF_STOCK',
    QUARANTINE: 'QUARANTINE'
  },
  BATCH_STATUS: {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    EXPIRED: 'EXPIRED',
    QUARANTINE: 'QUARANTINE'
  },
  TRANSACTION_TYPES: {
    RESERVE: 'RESERVE',
    RELEASE: 'RELEASE',
    DEDUCT: 'DEDUCT',
    RETURN: 'RETURN',
    ADJUSTMENT: 'ADJUSTMENT',
    QUARANTINE: 'QUARANTINE',
    RESTORE: 'RESTORE'
  }
} as const;

export type InventoryTransactionType =
  | 'RESERVE'
  | 'RELEASE'
  | 'DEDUCT'
  | 'RETURN'
  | 'ADJUSTMENT'
  | 'QUARANTINE'
  | 'RESTORE';

export type StockStatusType = 'IN_STOCK' | 'LOW' | 'OUT_OF_STOCK' | 'QUARANTINE';
export type BatchStatusType = 'ACTIVE' | 'INACTIVE' | 'EXPIRED' | 'QUARANTINE';
